### ISSUE TITLE
Collections Component

### ISSUE THREAD

**Issue by ziarparvaiz** [Cutting-Edge-Developers/code-ve-ceza#2]
### 📝 Todo

- [x] Collections Component Style
- [x] Create a file called Data.json, prepare the data in json format there
- [x] Then print to the screen
- [x] Must be responsive
